#%RAML 0.8
title: tongbao
version: 0.0.3
#---method---
#--string 类型的一定要考虑限制长度 ,这个长度会等数据库建完之后给出; 401错误用来表示未登陆状态下访问受限的url状态码--
/user:
  /register:
    description: 注册
    post:
      queryParameters:
        phoneNumber:
          displayName: phoneNumber
          type: string
          example: 15851813132
          required: true
          description: 必须为正确的手机号格式
        password:
          displayName: password
          type: string
          example: abc123
          required: true
          description: 限定最小长度,大于等于8
        type:
          displayName: type
          type: integer
          example: 0
          required: true
          description: 0表示货主, 1表示司机
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败)1(成功),
                  "errorMsg":(表示失败的原因，比如手机号已经注册)
                }
  /login:
    description: 登陆
    post:
      queryParameters:
        phoneNumber:
          displayName: phoneNumber
          type: string
          example: 15851813132
          required: true
        password:
          displayName: password
          type: string
          example: abc123
          required: true
        type:
          displayName: type
          type: integer
          example: 0
          required: true
          description: 0货主 1司机
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":(失败)1(成功),
                  "data"(只有登陆成功才会有):{"nickName":"夏明","iconUrl":"abc.com","point":23(积分),"money":34(账户余额),"token":用户识别的token,"id":1(用户id)}
                }
  /hasRegister:
    description: 判断手机号有没有被注册过
    post:
      queryParameters:
        phoneNumber:
          displayName: phoneNumber
          type: string
          example: 15851813132
          required: true
          description: 必须为正确的手机号格式
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(未注册)1(已注册)
                }
  /uploadPicture:
    description: 上传图片
    post:
      queryParameters:
        file:
          displayName: file
          type: file
          example: 
          required: true
          description: 这个使用post提交的文件，与在网页上上传文件类似
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败)1(成功),
                  "data": "url"(图片的url),
                  "errorMsg": 失败的原因
                }
  /auth/modifyNickName:
    description: 修改个人昵称
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        nickName:
          displayName: nickName
          type: string
          example: 小花
          required: true
          description: 修改后的用户名
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败)1(成功),
                  "errorMsg":失败的原因
                }
        401:
  /auth/modifyPassword:
    description: 修改密码
    post:
      queryParameters:
        token:
          displayName: token
          type: string
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用
        oldPassword:
          displayName: oldPassword
          type: string
          example: wree54654
          required: true
          description: 旧密
        newPassword:
          displayName: newPassword
          type: string
          example: fsdf23re
          required: true
          description: 新密码,长度大于等于8小于等于255
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败)1(成功),
                  "errorMsg":失败原因
                }
        401:
  /auth/modifyIcon:
    description: 修改个人头像
    post:
      queryParameters: 
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        iconUrl:
          displayName: iconUrl
          type: string 
          example: abc.com
          required: true
          description: 图片的url
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败)1(成功),
                  "errorMsg":失败原因
                }
        401:
  /auth/getContacts:
    description: 获取联系人列表
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "data":[{"id":1,"nickName":昵称,"phoneNum":12345,"type":(用户类型)0表示货主 1表示司机},
                          {"id":2,"nickName":昵称,"phoneNum":12345,"type":(用户类型)0表示货主 1表示司机},{}...] 
                } 
        401:
  /auth/getContactDetail:
    description: 获取联系人
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer 
          example: 1
          required: true
          description: 用于获取用户详情
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "data": {"id":1(用户id),"phoneNum":12345,"type":(用户类型)0表示货主 1表示司机,
                          "nickName":昵称,"sex":0男1女,"regTime":(注册时间)"2015-11-11 00:00:00"}
                }
        401:
  /auth/getMyMessages:
    description: 获取我的消息列表
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "data":[{"id":1,"type"(类型):0:订单被抢到（通知货主）1:订单完成（通知司机）2: 正在进行的订单被取消(通知司机)3：其他消息,
                            "content":消息内容,"hasRead"(是否已读):0未读,1已读,"time"(时间):消息产生的时间,
                            "objectId":type为012时表示订单id},{}]
                  "errorMsg": 失败原因
                }
        401:
  /auth/readMessage:
    description: 读消息
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer
          example: 1
          required: true
          description: 消息的id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败原因
                }
        401:
  /auth/deleteMessage: 
    description: 删除消息
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer
          example: 1
          required: true
          description: 消息的id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败原因
                }
        401:
  /auth/showAccount:
    description: 查看账单
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功)
                  "data":[
                      {
                      "type":(账单类型)0表示充值 1表示提现 2表示支付 3表示退款 4表示到帐, "time":(交易时间), "money":12(金额),
                      "order"(只有type为2,3,4时才有该值):{"id":1,"addressFrom":开始地点,"addressTo":终止地点}
                      },
                      {},...]
                } 
        401:
  /getAllTruckTypes:
    description: 获取所有车辆类型
    post:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功),
                  "errorMsg": 失败的原因 ,
                  "data": [{"type":0(类型),"name":"面包车","basePrice":起步价,"capacity":载重,"length":长度,"width":宽,"height":高,"overPrice":超公里费,"baseDistance":起步公里数(公里)},
                          {"type":1(类型),"name":"敞篷车","basePrice":起步价,"capacity":载重,"length":长度,"width":宽,"height":高,"overPrice":超公里费,"baseDistance":起步公里数(公里)},...]
                }
  /auth/recharge:
    description: 充值
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        money:
          displayName: money
          type: integer
          example: 23.3
          required: true
          description: 充值金额,因为这个工具不支持double,所以暂且写成int
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功)
                  "errorMsg": 失败的原因 
                }
        401:
  /auth/withdraw:
    description: 提现
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        money:
          displayName: money
          type: integer
          example: 23.3
          required: true
          description: 充值金额,因为这个工具不支持double,所以暂且写成int
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功)
                  "errorMsg": 失败的原因 
                }
        401:
/shipper:
  /auth/getFrequentDrivers:
    description: 获取常用司机列表
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "data":[{"id":1,"nickName":昵称,"phoneNum":12345},
                          {"id":2,"nickName":昵称,"phoneNum":12345},{}...] 
                }
        401:
  /auth/getFrequentAddresses:
    description: 获取常用地址列表
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "data":[{"lat":1,"name":12345,"lng":10},
                          {"lat":2,"name":12345,"lng":10},{}...] 
                }
        401:
  /auth/addFrequentDriver:
    description: 添加常用司机
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer 
          example: 1
          required: true
          description: 司机id，先根据手机号搜索得到的司机id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败原因
                }
        401:
  /auth/searchDriver:
    description: 根据手机号搜索司机(可以是模糊搜索)
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        phoneNum:
          displayName: phoneNum
          type: string
          example: 15950570277
          required: true
          description: 司机手机号
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "data":[{"id":1,"nickName":12345,"phoneNum":1595070372},
                          {"id":2,"nickName":12345,"phoneNum":1595070372},{}...] 
                }
        401:
  /auth/addFrequentAddress:
    description: 添加常用地址
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        address:
          displayName: address
          type: string
          example: 鼓楼区
          required: true
          description: 地址字符串，后面可能要根据百度地图提供的接口添加经纬度坐标
        lat:
          displayName: lat
          type: string
          example: 25.36
          description: 维度（double类型）
        lng:
          displayName: lng
          type: string
          example: 254.2
          description: 经度 （double类型）
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败原因
                }
        401:
  /auth/getDriversPosition:
    description: 获取所有司机目前最新的位置
    post: 
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
      responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "result":0(失败)1(成功),
                    "data":[{"driver_id":司机id,"collect_time":采集的时间点,"receive_time":接收到的时间点,"lat":纬度,"lng":经度},{"driver_id":司机id,"collect_time":采集的时间点,"receive_time":接收到的时间点,"lat":纬度,"lng":经度}...], 
                    "errorMsg":失败原因
                  }
          401:
  /auth/placeOrder:
    description: 下单
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        addressFrom:
          displayName: addressFrom
          type: string
          example: 汉口路22号
          required: true
          description: 发货地
        addressFromLat:
          displayName: addressFromLat
          type: string
          example: 38.8
          required: true
          description: 发货地纬度,应该是double类型
        addressFromLng:
          displayName: addressFromLng
          type: string
          example: 128.8
          required: true
          description: 发货地经度，应该是double类型
        addressTo:
          displayName: addressTo
          type: string 
          example: 汉口路55号
          required: true
          description: 收货地
        addressToLat:
          displayName: addressToLat
          type: string
          example: 38.9
          required: true
          description: 收货地纬度，应该是double类型
        addressToLng:
          displayName: addressTo
          type: string
          example: 128.8
          required: true
          description: 收货地经度，应该是double类型
        fromContactName:
          displayName: fromContactName
          description: 发货地联系人姓名
          example: abc
          required: false
          type: string
        fromContactPhone: 
          displayName: fromContactPhone
          description: 发货地联系人电话
          type: string
          required: false
          example: 12345667
        toContactName:
          displayName: toContactName
          description: 收货地联系人姓名
          example: abc
          required: false
          type: string
        toContactPhone: 
          displayName: toContactPhone
          description: 收货地联系人电话
          type: string
          required: false
          example: 12345667
        loadTime:
          displayName: loadTime
          type: string
          example: 2015-11-09 00:00:00,注意格式
          required: true
          description: 装车时间
        goodsType:
          displayName: goodsType
          type: string
          example: 食品
          required: false
          description: 货物类型
        goodsWeight:
          displayName: goodsWeight
          type: integer
          example: 4
          required: false
          description: 货物的重量,单位是千克
        goodsSize:
          displayName: goodsSize
          type: integer
          required: false
          description: 货物的体积, 单位是方
        truckTypes:
          displayName: truckTypes
          type: integer
          example: 1
          required: true
          description: 所需车辆类型数组,[1,2,3,4]
        remark: 
          displayName: remark
          type: string
          example: sdfasdfasdfasfd
          required: false
          description: 备注信息
        payType:
          displayName: payType
          type: integer
          example: 0(线上)/1(线下)
          required: true
          description: 支付方式
        price:
          displayName: price
          type: integer
          example: 100
          required: true
          description: 酬劳
      responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "result":0(失败)1(成功)2(找不到合适匹配的司机),
                    "errorMsg":失败原因
                  }
          401:
  /auth/splitOrder:
    description: 当下单失败时需要提示用户是否自动拆单，用户点击 是 调用的方法,需要再次传入订单信息
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        addressFrom:
          displayName: addressFrom
          type: string
          example: 汉口路22号
          required: true
          description: 发货地
        addressTo:
          displayName: addressTo
          type: string 
          example: 汉口路55号
          required: true
          description: 收货地
        fromContactName:
          displayName: fromContactName
          description: 发货地联系人姓名
          example: abc
          required: false
          type: string
        fromContactPhone: 
          displayName: fromContactPhone
          description: 发货地联系人电话
          type: string
          required: false
          example: 12345667
        toContactName:
          displayName: fromContactName
          description: 收货地联系人姓名
          example: abc
          required: false
          type: string
        toContactPhone: 
          displayName: fromContactPhone
          description: 收货地联系人电话
          type: string
          required: false
          example: 12345667
        loadTime:
          displayName: loadTime
          type: string
          example: 2015-11-09 00:00:00,注意格式
          required: true
          description: 装车时间
        goodsType:
          displayName: goodsType
          type: string
          example: 食品
          required: false
          description: 货物类型
        goodsWeight:
          displayName: goodsWeight
          type: integer
          example: 4
          required: false
          description: 货物的重量,单位是千克
        goodsSize:
          displayName: goodsSize
          type: integer
          required: false
          description: 货物的体积, 单位是方
        truckTypes:
          displayName: truckTypes
          type: integer
          example: 1
          required: true
          description: 所需车辆类型数组,[1,2,3,4]
        remark: 
          displayName: remark
          type: string
          example: sdfasdfasdfasfd
          required: false
          description: 备注信息
        payType:
          displayName: payType
          type: integer
          example: 0(线上)/1(线下)
          required: true
          description: 支付方式
        price:
          displayName: price
          type: integer
          example: 100
          required: true
          description: 酬劳
        distance:
          displayName: distance
          type: integer
          example: 100
          required: true
          description: 大致公里数,用于分配订单金额
      responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "result":0(失败)1(成功),
                    "errorMsg":失败原因
                  }
          401:
  /auth/evaluateOrder:
    description: 评论订单
    post:
        queryParameters:
          token:
            displayName: token
            type: string 
            example: sdfs234rrjkn2IFO
            required: true
            description: 用于识别用户
          id:
            displayName: id
            type: integer
            example: 2015121312423
            required: true
            description: 要评论的订单
          evaluatePoint:
            displayName: evaluatePoint
            type: integer
            example: 0,1,2,3,4,5
            required: true
            description: 评分
          evaluateContent:
            displayName: evaluate
            type: string
            example: 司机挺好的
            required: false
            description: 评价内容
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "result": 0(失败),1(成功),
                    "errorMsg": 失败的原因
                  }
          401:
  /auth/showMyOrderList:
    description: 查看订单列表
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        type:
          displayName: type
          description: 0表示尚未开始,1表示正在进行,2表示已经完成,3表示被取消
          required: true
          example: 0
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败的原因,
                  "data":[{"id":1(订单id),"time":"2015-11-29 00:00:00"(下单时间),"addressFrom":开始地点,"addressTo":终止地点,"money":12.2(金额),
                          "truckTypes":["小型面包车","中型客车",..],"fromContactName":起点联系人姓名,"fromContactPhone":起点联系人号码,
                          "toContactName":终点联系人姓名,"toContactPhone":终点联系人号码,"loadTime":装车时间},
                          {"id":2(订单id),"time":"2015-11-29 00:00:00"(下单时间),"addressFrom":开始地点,"addressTo":终止地点,"money":12.2(金额),
                          "truckTypes":["小型面包车","中型客车",..],"fromContactName":起点联系人姓名,"fromContactPhone":起点联系人号码,
                          "toContactName":终点联系人姓名,"toContactPhone":终点联系人号码,"loadTime":装车时间},
                  ...]
                }
        401:
  /auth/getOrderDetail:
    description: 显示订单详情，只能看到自己的订单
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          type: integer
          required: true
          description: 订单id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败的原因,
                  "data":{"id":1(订单id),"time":"2015-11-29 00:00:00"(下单时间),"addressFrom":开始地点,"addressTo":终止地点,"money":12.2(金额),
                          "truckTypes":["小型面包车","中型客车",..],"fromContactName":起点联系人姓名,"fromContactPhone":起点联系人号码,
                          "toContactName":终点联系人姓名,"toContactPhone":终点联系人号码,"loadTime":装车时间,"state":订单目前的状态
                          0:尚未被抢1:已经被抢，正在进行2:已经完成3:已经取消4:进行中取消，正在等待司机确认}
                } 
        401: 
  /auth/deleteOrder:
    description: 删除订单，注意这里并不是真正删除，只是设置对其不可见
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer
          example: 2015121312423
          required: true
          description: 要删除的订单
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功),
                  "errorMsg": 失败的原因	
                }
        401:
  /auth/cancelOrder:
    description: 取消订单
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer
          example: 2015121312423
          required: true
          description: 要取消的订单id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功),2(pending,表示取消正在进行中的订单)
                  "errorMsg": 失败的原因	
                }
        401:
  /auth/finishOrder:
    description: 结束订单
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer
          example: 1
          required: true
          description: 要结束的订单id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功)
                  "errorMsg": 失败的原因	
                }	
        401:
/driver:
  /auth/getTruckList:
    description: 获取一个司机的车辆列表
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败的原因,
                  "data":[{"id":1(车辆id),"truckNum":车牌号,"authState":审核状态(0未验证，1正在验证，2验证成功,3验证失败)},{},{}
                  ...]
                }
        401:
  /auth/getTruckDetail:
    description: 获取一辆车的具体信息
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer
          example: 12
          required: true
          description: 车辆id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败的原因,
                  "data":{"truckNum":车牌号,"authState":审核状态(0未验证，1正在验证，2验证成功,3验证失败),"typeName":车型名称,"length":车长,"capacity":载重,"phoneNum":随车电话,"realName":车主姓名}
                }
        401:
  /auth/removeTruck:
    description: 删除车辆信息
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        truckNum:
          displayName: truckNum
          type: string
          example: 苏Asdf
          required: true
          description: 车牌号
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(删除失败),1(删除成功)
                  "errorMsg": 失败的原因 
                }
        401:
  /auth/addTruck:
    description: 添加车辆信息
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        truckNum:
          displayName: truckNum
          type: string
          example: 苏Asdf
          required: true
          description: 车牌号
        truckType:
          displayName: type
          required: true
          example: 0
          type: integer
          description: 车辆类型
        phoneNum:
          type: string
          required: true
          example: 12121212
          displayName: phoneNum
          description: 随车电话
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(设置失败),1(设置成功)
                  "errorMsg": 失败的原因	
                }
        401:
  /auth/setRealNameAuthInfo:
    description: 设置实名认证信息
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        truckNum:
          displayName: truckNum
          type: string
          example: 苏Asdf
          required: true
          description: 车牌号
        realName:
          displayName: realName
          type: string
          example: 管登容
          required: true
          description: 真实姓名
        licenseNum:
          displayName: licenseNum
          required: true
          example: 121212121212
          type: string
          description: 驾驶证号码
        licensePicUrl:
          displayName: licensePicUrl
          type: string
          required: true
          example: asdf.com
          description: 驾驶证图像
        driverHeadPicUrl:
          type: string
          required: true
          example: sdfsdf.com
          displayName: driverHeadPicUrl
          description: 驾驶人头像照片
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(提交失败),1(提交成功)
                  "errorMsg": 失败的原因	
                }
        401:
  /auth/setTruckAuthInfo:
    description: 设置车辆认证信息
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        truckNum:
          displayName: truckNum
          type: string
          example: 苏Asdf
          required: true
          description: 车牌号
        truckHeadPicUrl:
          displayName: truckHeadPicUrl
          type: string
          required: true
          example: asdf.com
          description: 车头照图像url
        driveLicensePicUrl:
          type: string
          required: true
          example: sdfsdf.com
          displayName: driveLicensePicUrl
          description: 行驶证图像url
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(提交失败),1(提交成功)
                  "errorMsg": 失败的原因	
                }
        401:
  /auth/showMyOrderList:
    description: 显示订单列表
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        type:
          displayName: type
          description: 类型,1表示正在进行,2表示已经完成
          required: true
          example: 0
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败的原因,
                  "data":[{"id":1(订单id),"time":"2015-11-29 00:00:00"(下单时间),"addressFrom":开始地点,"addressTo":终止地点,"money":12.2(金额),
                          "truckTypes":["小型面包车","中型客车",..],"fromContactName":起点联系人姓名,"fromContactPhone":起点联系人号码,
                          "toContactName":终点联系人姓名,"toContactPhone":终点联系人号码,"loadTime":装车时间},
                          {"id":2(订单id),"time":"2015-11-29 00:00:00"(下单时间),"addressFrom":开始地点,"addressTo":终止地点,"money":12.2(金额),
                          "truckTypes":["小型面包车","中型客车",..],"fromContactName":起点联系人姓名,"fromContactPhone":起点联系人号码,
                          "toContactName":终点联系人姓名,"toContactPhone":终点联系人号码,"loadTime":装车时间},
                  ...]
                }
        401:
  /auth/cancelOrder:
    description: 取消订单
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: 订单id
          type: integer
          example: 2015121312423
          required: true
          description: 要取消的订单id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功)
                  "errorMsg": 失败的原因	
                }
        401:
  /auth/deleteOrder:
    description: 删除订单,注意这里并不是真正删除，只是设置对其不可见
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer
          example: 2015121312423
          required: true
          description: 要删除的订单
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功),
                  "errorMsg": 失败的原因	
                }
        401:
  /auth/grabOrder:
    description: 抢单
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          displayName: id
          type: integer
          example: 2015121312423
          required: true
          description: 要抢的订单
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功),
                  "errorMsg": 失败的原因	
                }
        401:
  /auth/updateMyPostion:
    description: 更新司机位置
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        collectTime:
          displayName: collectTime
          type: string
          example: 2015-11-11 11:11:11
          required: true
          description: 收集位置的时间点
        lat:
          displayName: lat
          example: 38.8737483
          required: true
          description: 纬度
        lng:
          displayName: lng
          example: 128.8737483
          required: true
          description: 经度
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result": 0(失败),1(成功),
                  "errorMsg": 失败的原因	
                }
        401:
  /auth/showAllOrders:
    description: 显示所有未被抢到的订单,根据起点终点筛选,起点终点的格式要尽快由百度地图确定,暂时定为string,查找string相同的起点终点
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        fromAddress:
          displayName: fromAddress
          type: string 
          example: 鼓楼区
          required: true
          description: 起点筛选
        toAddress:
          displayName: toAddress
          type: string 
          example: 玄武区
          required: true
          description: 终点筛选
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败的原因,
                  "data":[{"id":1(订单id),"time":"2015-11-29 00:00:00"(下单时间),"addressFrom":开始地点,"addressTo":终止地点,"money":12.2(金额),"lat":起点纬度,"lng":起点经度,
                          "truckTypes":["小型面包车","中型客车",..],"fromContactName":起点联系人姓名,"fromContactPhone":起点联系人号码,
                          "toContactName":终点联系人姓名,"toContactPhone":终点联系人号码,"loadTime":装车时间},
                            {"id":2(订单id),"time":"2015-11-29 00:00:00"(下单时间),"addressFrom":开始地点,"addressTo":终止地点,"money":12.2(金额),"lat":起点纬度,"lng":起点经度,
                          "truckTypes":["小型面包车","中型客车",..],"fromContactName":起点联系人姓名,"fromContactPhone":起点联系人号码,
                          "toContactName":终点联系人姓名,"toContactPhone":终点联系人号码,"loadTime":装车时间},
                  ...]
                }
        401:
  /auth/getOrderDetail:
    description: 显示订单详情，只能看到尚未被抢的以及被自己抢到的
    post:
      queryParameters:
        token:
          displayName: token
          type: string 
          example: sdfs234rrjkn2IFO
          required: true
          description: 用于识别用户
        id:
          type: integer
          required: true
          description: 订单id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0(失败),1(成功),
                  "errorMsg": 失败的原因,
                  "data":{"id":1(订单id),"time":"2015-11-29 00:00:00"(下单时间),"addressFrom":开始地点,"addressTo":终止地点,"money":12.2(金额),
                          "truckTypes":["小型面包车","中型客车",..],"fromContactName":起点联系人姓名,"fromContactPhone":起点联系人号码,
                          "toContactName":终点联系人姓名,"toContactPhone":终点联系人号码,"loadTime":装车时间,"state":订单目前的状态
                          0:尚未被抢1:已经被抢，正在进行2:进行中取消，正在等待司机确认4:已经完成}
                }
        401: 